cruel_summer:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: dbt_peat
      threads: 1
      type: postgres
      user: postgres
    uat:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: uat
      threads: 1
      type: postgres
      user: postgres
  target: dev
